packages:
- '.'
extra-deps:
- git: https://github.com/computationwithboundedresources/slogic.git
  commit: a925dd76e0432f13b105aa44657cd046cf959c9a
- git: https://github.com/computationwithboundedresources/tct-core.git
  commit: 5aba80ab385febb66f7236b99a1acf9db159a9d1
- git: https://github.com/computationwithboundedresources/tct-common.git
  commit: dbdbddf53b5c62c4c983a8025b7ef388f6f75563
- git: https://github.com/computationwithboundedresources/tct-its.git
  commit: 9dddf0c2341bebadec55cac05848de9eab9d0665
- git: https://github.com/computationwithboundedresources/lare.git
  commit: b81d3f3ad0b7d6911ae5a827a1e18645e1194377
- fgl-visualize-0.1.0.1
- dotgen-0.4.2
resolver: lts-5.12
# allow-newer: true
ghc-options:
  "$locals": -Wall -fno-warn-orphans -O3 -threaded
  "$everything": -O3

